### PR TITLE
New auth mechanism

### PR DESCRIPTION
**Pull request by yoooou**
Inspired by updates from hass-aarlo repo. Just trying to make Arlo login work by making minimal changes.

### CODE REVIEW

**Comment by mepster** [comment]
Thanks @yoooou, this works great for me, you are awesome.

@tchellomello you can probably merge, thanks for all your work. I run pyarlo every day.

**Comment by dscoular** [comment]
Hi @yoooou ,
I found I had to add a mechanism to bypass cloudflare:

```patch
$ diff -u __init__.py __init__.py~
--- __init__.py 2020-04-18 10:51:17.687413694 +1000
+++ __init__.py~        2020-04-17 18:41:56.000000000 +1000
@@ -2,7 +2,6 @@
 """Base Python Class file for Netgear Arlo camera module."""
 import logging
 import requests
-import cloudscraper

 from pyarlo.base_station import ArloBaseStation
 from pyarlo.camera import ArloCamera
@@ -42,7 +41,7 @@
         # set username and password
         self.__password = password
         self.__username = username
-        self.session = cloudscraper.CloudScraper() # requests.Session()
+        self.session = requests.Session()

         # login user
         self.login()
```
After this your fix worked perfectly for me!

**Comment by fermulator** [comment]
What are next steps to get this merged in?

**Comment by fermulator** [comment]
@tchellomello :exclamation: ?

**Comment by tchellomello** [comment]
@yoooou Thanks for your contribution. Are you planning to add the suggestion from @dscoular above?

**Comment by yoooou** [comment]
> @yoooou Thanks for your contribution. Are you planning to add the suggestion from @dscoular above?

TBH I don't have enough knowledge to tell whether @dscoular 's change should be included or not. It doesn't look like something neccesary at least for some of us it seems. Some clarifications/suggestions would be helpful.

**Comment by fermulator** [comment]
of note, i _did not_ require https://github.com/tchellomello/python-arlo/pull/115#issuecomment-615526829

**Comment by fermulator** [comment]
@tchellomello mergie mergie time? (let me know how I can help)

**Comment by TakesTheBiscuit** [comment]
👀

**Comment by tchellomello** [comment]
Sorry guys.. I'm looking for some maintainers to help to keep this code. If you are interested, please let me know.

**Pull request merged**
